version: '3'

services:
  frontend:
    build: ./react
    container_name: docker-frontend
    command: npm run start
    ports:
    - "3001:3000"
    stdin_open: true
    tty: true
    volumes:
    - ./react/src:/usr/src/app/src
